name: Install Dependencies & Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test-client-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'node'
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json

      - name: Install Dependencies
        working-directory: ./client
        run: npm install

      - name: Run Build
        working-directory: ./client
        run: npm run build
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: 'pk_test_bGlrZWQtdGFoci00NS5jbGVyay5hY2NvdW50cy5kZXYk'